// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_settings.sql

package db

import (
	"context"
)

const getAdminSettings = `-- name: GetAdminSettings :one
SELECT id, open_registration, instance_name, max_messages, max_message_chars, updated_at
FROM admin_settings
WHERE id = 1
`

func (q *Queries) GetAdminSettings(ctx context.Context) (AdminSetting, error) {
	row := q.db.QueryRowContext(ctx, getAdminSettings)
	var i AdminSetting
	err := row.Scan(
		&i.ID,
		&i.OpenRegistration,
		&i.InstanceName,
		&i.MaxMessages,
		&i.MaxMessageChars,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminSettings = `-- name: UpdateAdminSettings :exec
UPDATE admin_settings
SET open_registration = $1,
    instance_name = $2,
    max_messages = $3,
    max_message_chars = $4,
    updated_at = now()
WHERE id = 1
`

type UpdateAdminSettingsParams struct {
	OpenRegistration bool
	InstanceName     string
	MaxMessages      int32
	MaxMessageChars  int32
}

func (q *Queries) UpdateAdminSettings(ctx context.Context, arg UpdateAdminSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminSettings,
		arg.OpenRegistration,
		arg.InstanceName,
		arg.MaxMessages,
		arg.MaxMessageChars,
	)
	return err
}
