// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_reads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUnreadCounts = `-- name: GetUnreadCounts :many
SELECT
  c.id AS channel_id,
  COUNT(m.id)::int AS unread_count,
  COUNT(mm.user_id)::int AS mention_count
FROM channels c
LEFT JOIN channel_reads cr ON cr.channel_id = c.id AND cr.user_id = $1
LEFT JOIN messages m ON m.channel_id = c.id AND m.created_at > COALESCE(cr.last_read_at, '1970-01-01'::timestamptz)
LEFT JOIN message_mentions mm ON mm.message_id = m.id AND mm.user_id = $1
WHERE c.is_voice = false
GROUP BY c.id
`

type GetUnreadCountsRow struct {
	ChannelID    uuid.UUID
	UnreadCount  int32
	MentionCount int32
}

func (q *Queries) GetUnreadCounts(ctx context.Context, userID uuid.UUID) ([]GetUnreadCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadCountsRow
	for rows.Next() {
		var i GetUnreadCountsRow
		if err := rows.Scan(&i.ChannelID, &i.UnreadCount, &i.MentionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelRead = `-- name: UpsertChannelRead :exec
INSERT INTO channel_reads (user_id, channel_id, last_read_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id, channel_id) DO UPDATE SET last_read_at = NOW()
`

type UpsertChannelReadParams struct {
	UserID    uuid.UUID
	ChannelID uuid.UUID
}

func (q *Queries) UpsertChannelRead(ctx context.Context, arg UpsertChannelReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelRead, arg.UserID, arg.ChannelID)
	return err
}
