// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, topic, position, is_voice)
VALUES ($1, $2, $3, false)
RETURNING id, name, topic, is_voice, position, created_at
`

type CreateChannelParams struct {
	Name     string
	Topic    sql.NullString
	Position int32
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Topic, arg.Position)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.IsVoice,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, topic, is_voice, position, created_at FROM channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.IsVoice,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, topic, is_voice, position, created_at FROM channels
WHERE is_voice = false
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Topic,
			&i.IsVoice,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $1, topic = $2, position = $3
WHERE id = $4
RETURNING id, name, topic, is_voice, position, created_at
`

type UpdateChannelParams struct {
	Name     string
	Topic    sql.NullString
	Position int32
	ID       uuid.UUID
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Topic,
		&i.IsVoice,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
