// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm_pairs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDMPair = `-- name: CreateDMPair :one
INSERT INTO dm_pairs (user_a, user_b)
VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid))
ON CONFLICT (user_a, user_b) DO UPDATE SET user_a = dm_pairs.user_a
RETURNING id, user_a, user_b, created_at
`

type CreateDMPairParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) CreateDMPair(ctx context.Context, arg CreateDMPairParams) (DmPair, error) {
	row := q.db.QueryRowContext(ctx, createDMPair, arg.UserA, arg.UserB)
	var i DmPair
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
	)
	return i, err
}

const getDMPair = `-- name: GetDMPair :one
SELECT id, user_a, user_b, created_at FROM dm_pairs
WHERE id = $1
`

func (q *Queries) GetDMPair(ctx context.Context, id uuid.UUID) (DmPair, error) {
	row := q.db.QueryRowContext(ctx, getDMPair, id)
	var i DmPair
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
	)
	return i, err
}

const getDMPairByUsers = `-- name: GetDMPairByUsers :one
SELECT id, user_a, user_b, created_at FROM dm_pairs
WHERE user_a = LEAST($1::uuid, $2::uuid) AND user_b = GREATEST($1::uuid, $2::uuid)
`

type GetDMPairByUsersParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) GetDMPairByUsers(ctx context.Context, arg GetDMPairByUsersParams) (DmPair, error) {
	row := q.db.QueryRowContext(ctx, getDMPairByUsers, arg.UserA, arg.UserB)
	var i DmPair
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.CreatedAt,
	)
	return i, err
}

const listDMPairsForUser = `-- name: ListDMPairsForUser :many
SELECT dp.id, dp.user_a, dp.user_b, dp.created_at,
       u.id AS other_user_id, u.username AS other_username,
       u.display_name AS other_display_name, u.avatar_url AS other_avatar_url
FROM dm_pairs dp
JOIN users u ON u.id = CASE WHEN dp.user_a = $1 THEN dp.user_b ELSE dp.user_a END
WHERE dp.user_a = $1 OR dp.user_b = $1
ORDER BY dp.created_at DESC
`

type ListDMPairsForUserRow struct {
	ID               uuid.UUID
	UserA            uuid.UUID
	UserB            uuid.UUID
	CreatedAt        time.Time
	OtherUserID      uuid.UUID
	OtherUsername    string
	OtherDisplayName sql.NullString
	OtherAvatarUrl   sql.NullString
}

func (q *Queries) ListDMPairsForUser(ctx context.Context, userA uuid.UUID) ([]ListDMPairsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDMPairsForUser, userA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDMPairsForUserRow
	for rows.Next() {
		var i ListDMPairsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserA,
			&i.UserB,
			&i.CreatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.OtherDisplayName,
			&i.OtherAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
