// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emotes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEmote = `-- name: CreateEmote :one
INSERT INTO custom_emotes (name, filename, uploaded_by)
VALUES ($1, $2, $3)
RETURNING id, name, filename, uploaded_by, created_at
`

type CreateEmoteParams struct {
	Name       string
	Filename   string
	UploadedBy uuid.UUID
}

func (q *Queries) CreateEmote(ctx context.Context, arg CreateEmoteParams) (CustomEmote, error) {
	row := q.db.QueryRowContext(ctx, createEmote, arg.Name, arg.Filename, arg.UploadedBy)
	var i CustomEmote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmote = `-- name: DeleteEmote :one
DELETE FROM custom_emotes
WHERE id = $1
RETURNING filename
`

func (q *Queries) DeleteEmote(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteEmote, id)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getEmoteByID = `-- name: GetEmoteByID :one
SELECT id, name, filename, uploaded_by, created_at
FROM custom_emotes
WHERE id = $1
`

func (q *Queries) GetEmoteByID(ctx context.Context, id uuid.UUID) (CustomEmote, error) {
	row := q.db.QueryRowContext(ctx, getEmoteByID, id)
	var i CustomEmote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEmoteByName = `-- name: GetEmoteByName :one
SELECT id, name, filename, uploaded_by, created_at
FROM custom_emotes
WHERE name = $1
`

func (q *Queries) GetEmoteByName(ctx context.Context, name string) (CustomEmote, error) {
	row := q.db.QueryRowContext(ctx, getEmoteByName, name)
	var i CustomEmote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEmotesByNames = `-- name: GetEmotesByNames :many
SELECT id, name, filename, uploaded_by, created_at
FROM custom_emotes
WHERE name = ANY($1::text[])
`

func (q *Queries) GetEmotesByNames(ctx context.Context, dollar_1 []string) ([]CustomEmote, error) {
	rows, err := q.db.QueryContext(ctx, getEmotesByNames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomEmote
	for rows.Next() {
		var i CustomEmote
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Filename,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmotes = `-- name: ListEmotes :many
SELECT id, name, filename, uploaded_by, created_at
FROM custom_emotes
ORDER BY name
`

func (q *Queries) ListEmotes(ctx context.Context) ([]CustomEmote, error) {
	rows, err := q.db.QueryContext(ctx, listEmotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomEmote
	for rows.Next() {
		var i CustomEmote
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Filename,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
