// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invite_codes.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInviteCode = `-- name: CreateInviteCode :one
INSERT INTO invite_codes (code, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, code, max_uses, use_count, expires_at, created_by, created_at
`

type CreateInviteCodeParams struct {
	Code      string
	MaxUses   sql.NullInt32
	ExpiresAt sql.NullTime
	CreatedBy uuid.UUID
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (InviteCode, error) {
	row := q.db.QueryRowContext(ctx, createInviteCode,
		arg.Code,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInviteCode = `-- name: DeleteInviteCode :exec
DELETE FROM invite_codes WHERE id = $1
`

func (q *Queries) DeleteInviteCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInviteCode, id)
	return err
}

const getInviteCodeByCode = `-- name: GetInviteCodeByCode :one
SELECT id, code, max_uses, use_count, expires_at, created_by, created_at FROM invite_codes WHERE code = $1
`

func (q *Queries) GetInviteCodeByCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRowContext(ctx, getInviteCodeByCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteCodeUseCount = `-- name: IncrementInviteCodeUseCount :exec
UPDATE invite_codes SET use_count = use_count + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteCodeUseCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementInviteCodeUseCount, id)
	return err
}

const listInviteCodes = `-- name: ListInviteCodes :many
SELECT ic.id, ic.code, ic.max_uses, ic.use_count, ic.expires_at, ic.created_by, ic.created_at, u.username AS created_by_username
FROM invite_codes ic
JOIN users u ON u.id = ic.created_by
ORDER BY ic.created_at DESC
`

type ListInviteCodesRow struct {
	ID                uuid.UUID
	Code              string
	MaxUses           sql.NullInt32
	UseCount          int32
	ExpiresAt         sql.NullTime
	CreatedBy         uuid.UUID
	CreatedAt         time.Time
	CreatedByUsername string
}

func (q *Queries) ListInviteCodes(ctx context.Context) ([]ListInviteCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInviteCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInviteCodesRow
	for rows.Next() {
		var i ListInviteCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
