// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteMediaUploadsByIDs = `-- name: DeleteMediaUploadsByIDs :exec
DELETE FROM media_uploads WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteMediaUploadsByIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMediaUploadsByIDs, pq.Array(dollar_1))
	return err
}

const extendMediaUploadExpiry = `-- name: ExtendMediaUploadExpiry :exec
UPDATE media_uploads SET expires_at = NOW() + INTERVAL '24 hours' WHERE id = $1
`

func (q *Queries) ExtendMediaUploadExpiry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, extendMediaUploadExpiry, id)
	return err
}

const getExpiredMediaUploads = `-- name: GetExpiredMediaUploads :many
SELECT id, bucket_key FROM media_uploads WHERE expires_at < NOW()
`

type GetExpiredMediaUploadsRow struct {
	ID        uuid.UUID
	BucketKey string
}

func (q *Queries) GetExpiredMediaUploads(ctx context.Context) ([]GetExpiredMediaUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredMediaUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredMediaUploadsRow
	for rows.Next() {
		var i GetExpiredMediaUploadsRow
		if err := rows.Scan(&i.ID, &i.BucketKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaUploadByHash = `-- name: GetMediaUploadByHash :one
SELECT id, uploader_id, bucket_key, content_hash, media_type, expires_at, created_at FROM media_uploads WHERE content_hash = $1 LIMIT 1
`

func (q *Queries) GetMediaUploadByHash(ctx context.Context, contentHash string) (MediaUpload, error) {
	row := q.db.QueryRowContext(ctx, getMediaUploadByHash, contentHash)
	var i MediaUpload
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.BucketKey,
		&i.ContentHash,
		&i.MediaType,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMediaUpload = `-- name: InsertMediaUpload :one
INSERT INTO media_uploads (uploader_id, bucket_key, content_hash, media_type)
VALUES ($1, $2, $3, $4)
RETURNING id, uploader_id, bucket_key, content_hash, media_type, expires_at, created_at
`

type InsertMediaUploadParams struct {
	UploaderID  uuid.UUID
	BucketKey   string
	ContentHash string
	MediaType   string
}

func (q *Queries) InsertMediaUpload(ctx context.Context, arg InsertMediaUploadParams) (MediaUpload, error) {
	row := q.db.QueryRowContext(ctx, insertMediaUpload,
		arg.UploaderID,
		arg.BucketKey,
		arg.ContentHash,
		arg.MediaType,
	)
	var i MediaUpload
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.BucketKey,
		&i.ContentHash,
		&i.MediaType,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
