// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteMentionsByMessage = `-- name: DeleteMentionsByMessage :exec
DELETE FROM message_mentions WHERE message_id = $1
`

func (q *Queries) DeleteMentionsByMessage(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMentionsByMessage, messageID)
	return err
}

const insertMention = `-- name: InsertMention :exec
INSERT INTO message_mentions (message_id, user_id) VALUES ($1, $2)
`

type InsertMentionParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) InsertMention(ctx context.Context, arg InsertMentionParams) error {
	_, err := q.db.ExecContext(ctx, insertMention, arg.MessageID, arg.UserID)
	return err
}
