// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countChannels = `-- name: CountChannels :one
SELECT count(*) FROM channels
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type CreateMessageParams struct {
	ChannelID uuid.NullUUID
	UserID    uuid.UUID
	Content   string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteOldestMessages = `-- name: DeleteOldestMessages :exec
DELETE FROM messages
WHERE id IN (
  SELECT id FROM messages
  WHERE pinned = false
  ORDER BY created_at ASC
  LIMIT $1
)
`

func (q *Queries) DeleteOldestMessages(ctx context.Context, limit int32) error {
	_, err := q.db.ExecContext(ctx, deleteOldestMessages, limit)
	return err
}

const getLatestMessagesByChannel = `-- name: GetLatestMessagesByChannel :many
SELECT sub.id, sub.channel_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.channel_id = $1
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetLatestMessagesByChannelRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetLatestMessagesByChannel(ctx context.Context, channelID uuid.NullUUID) ([]GetLatestMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesByChannelRow
	for rows.Next() {
		var i GetLatestMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByChannel = `-- name: GetMessagesByChannel :many
SELECT sub.id, sub.channel_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.channel_id = $1
    AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetMessagesByChannelParams struct {
	ChannelID  uuid.NullUUID
	BeforeTime time.Time
	BeforeID   uuid.UUID
}

type GetMessagesByChannelRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetMessagesByChannel(ctx context.Context, arg GetMessagesByChannelParams) ([]GetMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannel, arg.ChannelID, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChannelRow
	for rows.Next() {
		var i GetMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages
SET content = $1, edited_at = now()
WHERE id = $2
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type UpdateMessageContentParams struct {
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessageContent, arg.Content, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}
