// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countChannels = `-- name: CountChannels :one
SELECT count(*) FROM channels
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDMMessage = `-- name: CreateDMMessage :one
INSERT INTO messages (dm_pair_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type CreateDMMessageParams struct {
	DmPairID uuid.NullUUID
	UserID   uuid.UUID
	Content  string
}

func (q *Queries) CreateDMMessage(ctx context.Context, arg CreateDMMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createDMMessage, arg.DmPairID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type CreateMessageParams struct {
	ChannelID uuid.NullUUID
	UserID    uuid.UUID
	Content   string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteOldestMessages = `-- name: DeleteOldestMessages :exec
DELETE FROM messages
WHERE id IN (
  SELECT id FROM messages
  WHERE pinned = false
  ORDER BY created_at ASC
  LIMIT $1
)
`

func (q *Queries) DeleteOldestMessages(ctx context.Context, limit int32) error {
	_, err := q.db.ExecContext(ctx, deleteOldestMessages, limit)
	return err
}

const getDMMessagesByPair = `-- name: GetDMMessagesByPair :many
SELECT sub.id, sub.dm_pair_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.dm_pair_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.dm_pair_id = $1
    AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetDMMessagesByPairParams struct {
	DmPairID   uuid.NullUUID
	BeforeTime time.Time
	BeforeID   uuid.UUID
}

type GetDMMessagesByPairRow struct {
	ID          uuid.UUID
	DmPairID    uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetDMMessagesByPair(ctx context.Context, arg GetDMMessagesByPairParams) ([]GetDMMessagesByPairRow, error) {
	rows, err := q.db.QueryContext(ctx, getDMMessagesByPair, arg.DmPairID, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDMMessagesByPairRow
	for rows.Next() {
		var i GetDMMessagesByPairRow
		if err := rows.Scan(
			&i.ID,
			&i.DmPairID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDMMessages = `-- name: GetLatestDMMessages :many
SELECT sub.id, sub.dm_pair_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.dm_pair_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.dm_pair_id = $1
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetLatestDMMessagesRow struct {
	ID          uuid.UUID
	DmPairID    uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetLatestDMMessages(ctx context.Context, dmPairID uuid.NullUUID) ([]GetLatestDMMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestDMMessages, dmPairID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestDMMessagesRow
	for rows.Next() {
		var i GetLatestDMMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DmPairID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMessagesByChannel = `-- name: GetLatestMessagesByChannel :many
SELECT sub.id, sub.channel_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.channel_id = $1
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetLatestMessagesByChannelRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetLatestMessagesByChannel(ctx context.Context, channelID uuid.NullUUID) ([]GetLatestMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesByChannelRow
	for rows.Next() {
		var i GetLatestMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesAfterCursor = `-- name: GetMessagesAfterCursor :many
SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
       u.username, u.display_name, u.avatar_url
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1
  AND (m.created_at > $2 OR (m.created_at = $2 AND m.id > $3))
ORDER BY m.created_at ASC, m.id ASC
LIMIT 50
`

type GetMessagesAfterCursorParams struct {
	ChannelID uuid.NullUUID
	AfterTime time.Time
	AfterID   uuid.UUID
}

type GetMessagesAfterCursorRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetMessagesAfterCursor(ctx context.Context, arg GetMessagesAfterCursorParams) ([]GetMessagesAfterCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesAfterCursor, arg.ChannelID, arg.AfterTime, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesAfterCursorRow
	for rows.Next() {
		var i GetMessagesAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesAroundTarget = `-- name: GetMessagesAroundTarget :many
SELECT sub.id, sub.channel_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  (
    SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
           u.username, u.display_name, u.avatar_url
    FROM messages m
    JOIN users u ON u.id = m.user_id
    WHERE m.channel_id = $1
      AND (m.created_at < (SELECT t.created_at FROM messages t WHERE t.id = $2)
           OR (m.created_at = (SELECT t.created_at FROM messages t WHERE t.id = $2) AND m.id < $2))
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 25
  )
  UNION ALL
  (
    SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
           u.username, u.display_name, u.avatar_url
    FROM messages m
    JOIN users u ON u.id = m.user_id
    WHERE m.id = $2
  )
  UNION ALL
  (
    SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
           u.username, u.display_name, u.avatar_url
    FROM messages m
    JOIN users u ON u.id = m.user_id
    WHERE m.channel_id = $1
      AND (m.created_at > (SELECT t.created_at FROM messages t WHERE t.id = $2)
           OR (m.created_at = (SELECT t.created_at FROM messages t WHERE t.id = $2) AND m.id > $2))
    ORDER BY m.created_at ASC, m.id ASC
    LIMIT 25
  )
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetMessagesAroundTargetParams struct {
	ChannelID uuid.NullUUID
	TargetID  uuid.UUID
}

type GetMessagesAroundTargetRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetMessagesAroundTarget(ctx context.Context, arg GetMessagesAroundTargetParams) ([]GetMessagesAroundTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesAroundTarget, arg.ChannelID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesAroundTargetRow
	for rows.Next() {
		var i GetMessagesAroundTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByChannel = `-- name: GetMessagesByChannel :many
SELECT sub.id, sub.channel_id, sub.user_id, sub.content, sub.pinned, sub.edited_at, sub.created_at,
       sub.username, sub.display_name, sub.avatar_url
FROM (
  SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
         u.username, u.display_name, u.avatar_url
  FROM messages m
  JOIN users u ON u.id = m.user_id
  WHERE m.channel_id = $1
    AND (m.created_at < $2 OR (m.created_at = $2 AND m.id < $3))
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 50
) sub
ORDER BY sub.created_at ASC, sub.id ASC
`

type GetMessagesByChannelParams struct {
	ChannelID  uuid.NullUUID
	BeforeTime time.Time
	BeforeID   uuid.UUID
}

type GetMessagesByChannelRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetMessagesByChannel(ctx context.Context, arg GetMessagesByChannelParams) ([]GetMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannel, arg.ChannelID, arg.BeforeTime, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChannelRow
	for rows.Next() {
		var i GetMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinnedDMMessages = `-- name: GetPinnedDMMessages :many
SELECT m.id, m.dm_pair_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
       u.username, u.display_name, u.avatar_url
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.dm_pair_id = $1 AND m.pinned = true
ORDER BY m.created_at DESC
`

type GetPinnedDMMessagesRow struct {
	ID          uuid.UUID
	DmPairID    uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetPinnedDMMessages(ctx context.Context, dmPairID uuid.NullUUID) ([]GetPinnedDMMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPinnedDMMessages, dmPairID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPinnedDMMessagesRow
	for rows.Next() {
		var i GetPinnedDMMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DmPairID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinnedMessagesByChannel = `-- name: GetPinnedMessagesByChannel :many
SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
       u.username, u.display_name, u.avatar_url
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1 AND m.pinned = true
ORDER BY m.created_at DESC
`

type GetPinnedMessagesByChannelRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
}

func (q *Queries) GetPinnedMessagesByChannel(ctx context.Context, channelID uuid.NullUUID) ([]GetPinnedMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getPinnedMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPinnedMessagesByChannelRow
	for rows.Next() {
		var i GetPinnedMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.channel_id, m.user_id, m.content, m.pinned, m.edited_at, m.created_at,
       u.username, u.display_name, u.avatar_url, c.name AS channel_name
FROM messages m
JOIN users u ON u.id = m.user_id
JOIN channels c ON c.id = m.channel_id
WHERE m.channel_id IS NOT NULL
  AND ($1::uuid IS NULL OR m.channel_id = $1)
  AND ($2::uuid IS NULL OR m.user_id = $2)
  AND ($3::timestamptz IS NULL OR m.created_at >= $3)
  AND ($4::timestamptz IS NULL OR m.created_at <= $4)
  AND ($5::text IS NULL OR to_tsvector('english', m.content) @@ plainto_tsquery('english', $5))
ORDER BY m.created_at DESC
LIMIT 50
`

type SearchMessagesParams struct {
	ChannelID  uuid.NullUUID
	AuthorID   uuid.NullUUID
	AfterTime  sql.NullTime
	BeforeTime sql.NullTime
	Query      sql.NullString
}

type SearchMessagesRow struct {
	ID          uuid.UUID
	ChannelID   uuid.NullUUID
	UserID      uuid.UUID
	Content     string
	Pinned      bool
	EditedAt    sql.NullTime
	CreatedAt   time.Time
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
	ChannelName string
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages,
		arg.ChannelID,
		arg.AuthorID,
		arg.AfterTime,
		arg.BeforeTime,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.Pinned,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessagePinned = `-- name: SetMessagePinned :one
UPDATE messages SET pinned = $2 WHERE id = $1
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type SetMessagePinnedParams struct {
	ID     uuid.UUID
	Pinned bool
}

func (q *Queries) SetMessagePinned(ctx context.Context, arg SetMessagePinnedParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, setMessagePinned, arg.ID, arg.Pinned)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages
SET content = $1, edited_at = now()
WHERE id = $2
RETURNING id, channel_id, dm_pair_id, user_id, content, pinned, edited_at, created_at
`

type UpdateMessageContentParams struct {
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessageContent, arg.Content, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmPairID,
		&i.UserID,
		&i.Content,
		&i.Pinned,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}
