// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID        uuid.UUID
	Name      string
	Topic     sql.NullString
	IsVoice   bool
	Position  int32
	CreatedAt time.Time
}

type ChannelRead struct {
	UserID     uuid.UUID
	ChannelID  uuid.UUID
	LastReadAt time.Time
}

type CustomEmote struct {
	ID         uuid.UUID
	Name       string
	Filename   string
	UploadedBy uuid.UUID
	CreatedAt  time.Time
}

type DmPair struct {
	ID        uuid.UUID
	UserA     uuid.UUID
	UserB     uuid.UUID
	CreatedAt time.Time
}

type Message struct {
	ID        uuid.UUID
	ChannelID uuid.NullUUID
	DmPairID  uuid.NullUUID
	UserID    uuid.UUID
	Content   string
	Pinned    bool
	EditedAt  sql.NullTime
	CreatedAt time.Time
}

type MessageMention struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}

type PinnedMessage struct {
	ID        uuid.UUID
	ChannelID uuid.NullUUID
	DmPairID  uuid.NullUUID
	UserID    uuid.UUID
	Content   string
	Pinned    bool
	EditedAt  sql.NullTime
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	DisplayName  sql.NullString
	AvatarUrl    sql.NullString
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Color        sql.NullString
}
