// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, display_name, is_admin, supabase_id, needs_username)
VALUES ($1, '', $2, $3, $4, $5)
RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username
`

type CreateUserParams struct {
	Username      string
	DisplayName   sql.NullString
	IsAdmin       bool
	SupabaseID    sql.NullString
	NeedsUsername bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.IsAdmin,
		arg.SupabaseID,
		arg.NeedsUsername,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserBannedBySupabaseID = `-- name: GetUserBannedBySupabaseID :one
SELECT banned FROM users WHERE supabase_id = $1
`

func (q *Queries) GetUserBannedBySupabaseID(ctx context.Context, supabaseID sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, getUserBannedBySupabaseID, supabaseID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const getUserBySupabaseID = `-- name: GetUserBySupabaseID :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username FROM users WHERE supabase_id = $1
`

func (q *Queries) GetUserBySupabaseID(ctx context.Context, supabaseID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySupabaseID, supabaseID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id, username FROM users WHERE username = ANY($1::text[])
`

type GetUsersByUsernamesRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByUsernames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByUsernamesRow
	for rows.Next() {
		var i GetUsersByUsernamesRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, avatar_url, color, is_admin, banned FROM users ORDER BY username
`

type ListUsersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
	Color       sql.NullString
	IsAdmin     bool
	Banned      bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Color,
			&i.IsAdmin,
			&i.Banned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2, updated_at = now() WHERE id = $1
`

type SetUserAdminParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users SET banned = $2, updated_at = now() WHERE id = $1
`

type SetUserBannedParams struct {
	ID     uuid.UUID
	Banned bool
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) error {
	_, err := q.db.ExecContext(ctx, setUserBanned, arg.ID, arg.Banned)
	return err
}

const setUserUsername = `-- name: SetUserUsername :one
UPDATE users SET username = $2, needs_username = false, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username
`

type SetUserUsernameParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) SetUserUsername(ctx context.Context, arg SetUserUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const updateUserAvatarUrl = `-- name: UpdateUserAvatarUrl :one
UPDATE users SET avatar_url = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username
`

type UpdateUserAvatarUrlParams struct {
	ID        uuid.UUID
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateUserAvatarUrl(ctx context.Context, arg UpdateUserAvatarUrlParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatarUrl, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const updateUserColor = `-- name: UpdateUserColor :one
UPDATE users SET color = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username
`

type UpdateUserColorParams struct {
	ID    uuid.UUID
	Color sql.NullString
}

func (q *Queries) UpdateUserColor(ctx context.Context, arg UpdateUserColorParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserColor, arg.ID, arg.Color)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users SET display_name = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, supabase_id, banned, needs_username
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName sql.NullString
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.SupabaseID,
		&i.Banned,
		&i.NeedsUsername,
	)
	return i, err
}
