// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const clearPasswordResetToken = `-- name: ClearPasswordResetToken :exec
UPDATE users SET password_reset_token = NULL, password_reset_expires_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearPasswordResetToken, id)
	return err
}

const clearUserTOTP = `-- name: ClearUserTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled = false, recovery_codes = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearUserTOTP, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, display_name, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUserByEmailVerifyToken = `-- name: GetUserByEmailVerifyToken :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at FROM users WHERE email_verify_token = $1 AND email_verify_expires_at > now()
`

func (q *Queries) GetUserByEmailVerifyToken(ctx context.Context, emailVerifyToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailVerifyToken, emailVerifyToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at FROM users WHERE password_reset_token = $1 AND password_reset_expires_at > now()
`

func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, passwordResetToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPasswordResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id, username FROM users WHERE username = ANY($1::text[])
`

type GetUsersByUsernamesRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByUsernames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByUsernamesRow
	for rows.Next() {
		var i GetUsersByUsernamesRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, avatar_url, color, is_admin, banned FROM users ORDER BY username
`

type ListUsersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName sql.NullString
	AvatarUrl   sql.NullString
	Color       sql.NullString
	IsAdmin     bool
	Banned      bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Color,
			&i.IsAdmin,
			&i.Banned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true, email_verify_token = NULL, email_verify_expires_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const setEmailVerifyToken = `-- name: SetEmailVerifyToken :exec
UPDATE users SET email_verify_token = $2, email_verify_expires_at = $3, updated_at = now() WHERE id = $1
`

type SetEmailVerifyTokenParams struct {
	ID                   uuid.UUID
	EmailVerifyToken     sql.NullString
	EmailVerifyExpiresAt sql.NullTime
}

func (q *Queries) SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error {
	_, err := q.db.ExecContext(ctx, setEmailVerifyToken, arg.ID, arg.EmailVerifyToken, arg.EmailVerifyExpiresAt)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users SET password_reset_token = $2, password_reset_expires_at = $3, updated_at = now() WHERE id = $1
`

type SetPasswordResetTokenParams struct {
	ID                     uuid.UUID
	PasswordResetToken     sql.NullString
	PasswordResetExpiresAt sql.NullTime
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetToken, arg.PasswordResetExpiresAt)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2, updated_at = now() WHERE id = $1
`

type SetUserAdminParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users SET banned = $2, updated_at = now() WHERE id = $1
`

type SetUserBannedParams struct {
	ID     uuid.UUID
	Banned bool
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) error {
	_, err := q.db.ExecContext(ctx, setUserBanned, arg.ID, arg.Banned)
	return err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const setUserRecoveryCodes = `-- name: SetUserRecoveryCodes :exec
UPDATE users SET recovery_codes = $2, updated_at = now() WHERE id = $1
`

type SetUserRecoveryCodesParams struct {
	ID            uuid.UUID
	RecoveryCodes []string
}

func (q *Queries) SetUserRecoveryCodes(ctx context.Context, arg SetUserRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, setUserRecoveryCodes, arg.ID, pq.Array(arg.RecoveryCodes))
	return err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users SET totp_secret = $2, totp_enabled = $3, recovery_codes = $4, updated_at = now() WHERE id = $1
`

type SetUserTOTPSecretParams struct {
	ID            uuid.UUID
	TotpSecret    sql.NullString
	TotpEnabled   bool
	RecoveryCodes []string
}

func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTPSecret,
		arg.ID,
		arg.TotpSecret,
		arg.TotpEnabled,
		pq.Array(arg.RecoveryCodes),
	)
	return err
}

const updateUserAvatarUrl = `-- name: UpdateUserAvatarUrl :one
UPDATE users SET avatar_url = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at
`

type UpdateUserAvatarUrlParams struct {
	ID        uuid.UUID
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateUserAvatarUrl(ctx context.Context, arg UpdateUserAvatarUrlParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatarUrl, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const updateUserColor = `-- name: UpdateUserColor :one
UPDATE users SET color = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at
`

type UpdateUserColorParams struct {
	ID    uuid.UUID
	Color sql.NullString
}

func (q *Queries) UpdateUserColor(ctx context.Context, arg UpdateUserColorParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserColor, arg.ID, arg.Color)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users SET display_name = $2, updated_at = now() WHERE id = $1 RETURNING id, username, password_hash, display_name, avatar_url, is_admin, created_at, updated_at, color, banned, email, email_verified, email_verify_token, email_verify_expires_at, totp_secret, totp_enabled, recovery_codes, password_reset_token, password_reset_expires_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName sql.NullString
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Banned,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpiresAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		pq.Array(&i.RecoveryCodes),
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}
